---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
type: Opaque
stringData:
  user: "admin"
  password: "password"