---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: minio
      port: 9000
      targetPort: minio
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  type: ClusterIP
  ports:
    - name: minio
      port: 9000
      targetPort: minio
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/instance: minio
  serviceName: minio-headless
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/instance: minio
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/minio/v2/metrics/cluster"
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: minio
                    app.kubernetes.io/instance: minio
                namespaces:
                  - "minio"
                topologyKey: kubernetes.io/hostname
              weight: 100
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: minio
                    operator: In
                    values:
                      - "yes"
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: init-configs
          image: busybox:latest
          imagePullPolicy: "IfNotPresent"
          command:
            - sh
            - -c
            - |
              if [ ! -d /data-0/data ]; then
                mkdir /data-0/data
                chown 1001:1001 /data-0/data
              fi
              if [ ! -d /data-1/data ]; then
                mkdir /data-1/data
                chown 1001:1001 /data-1/data
              fi
              if [ ! -d /data-2/data ]; then
                mkdir /data-2/data
                chown 1001:1001 /data-2/data
              fi
              if [ ! -d /data-3/data ]; then
                mkdir /data-3/data
                chown 1001:1001 /data-3/data
              fi
          volumeMounts:
            - name: data-0
              mountPath: /data-0
            - name: data-1
              mountPath: /data-1
            - name: data-2
              mountPath: /data-2
            - name: data-3
              mountPath: /data-3
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MINIO_DISTRIBUTED_MODE_ENABLED
              value: "yes"
            - name: MINIO_DISTRIBUTED_NODES
              value: "minio-{0...3}.mi-headless.minio.svc.cluster.local/data-{0...3}/data"
            - name: MINIO_SCHEME
              value: "http"
            - name: MINIO_FORCE_NEW_KEYS
              value: "no"
            - name: MINIO_ROOT_USER # MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: user
            - name: MINIO_ROOT_PASSWORD # MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: password
            - name: MINIO_SKIP_CLIENT
              value: "yes"
            - name: MINIO_BROWSER
              value: "off"
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
          ports:
            - name: minio
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: minio
              scheme: "HTTP"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: minio
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - mountPath: /data-0
              name: data-0
            - mountPath: /data-1
              name: data-1
            - mountPath: /data-2
              name: data-2
            - mountPath: /data-3
              name: data-3
      volumes:
        - hostPath:
            path: /var/data-0
            type: DirectoryOrCreate
          name: data-0
        - hostPath:
            path: /var/data-1
            type: DirectoryOrCreate
          name: data-1
        - hostPath:
            path: /var/data-2
            type: DirectoryOrCreate
          name: data-2
        - hostPath:
            path: /var/data-3
            type: DirectoryOrCreate
          name: data-3